const obj1 = new Promise( (resolve, reject) => {
    setTimeout( () => {
        let arr = [1,2];
        resolve(arr);
        reject('Somethign went wrong!');
    }, 2000);
})

// then() , catch()

const excutePromise = (obj1) => {
    obj1.then( (res) => {
        console.log(res);

        excuteSecondPromise(res)
        .then((result)=> {
            console.log(result)
            excuteThirdPromise(result)
            .then( (response) => {
                console.log(response)
            })
            .catch( (e) => {console.log(e)} )
        })
        .catch((err) => {console.log(err)})

    })
    .catch( (err) => {
        console.log(err)
    })
}

excutePromise(obj1);